name: Testing
on: 
  push:
    branches:
      - main
jobs:
  lint:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: CI
        run: npm ci
      - name: format
        run: npm run format
      - name: useremail
        run: git config --global user.email "hi@parthiv.dev"
      - name: username
        run: git config --global user.name "shapedgod"
      - name: add changes
        run: git add .
      - name: commit
        run: git commit -m "Formatted"
      - name: push
        run: git push -u origin main
